name: CI for IsEvenModul

on:
  push:
    branches: [main]

jobs:

  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: '64'
    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install flake8
    - name: Run main tests with flake8
      run: |
         python -m flake8 main.py
    - name: Run main tests with unittest
      run: |
         python -m unittest tests.py
